config/routes.rb
StaffHols::Application.routes.draw do
  get "admin/index"

  get "calendar/show"

  authenticated :user do
    root :to => 'booked_holidays#index'
  end
  root :to => "booked_holidays#index"
  devise_for :users
  resources :users
  resources :booked_holidays do
    collection do
      post :approve
    end
    member do
      get :approve_deletion
      post :confirm_deletion
    end
  end
end

app/models/booked_holiday.rb
# == Schema Information
#
# Table name: booked_holidays
#
#  id                     :integer          not null, primary key
#  user_id                :integer
#  holiday_year_id        :integer
#  start_date             :date
#  half_day_on_start_date :boolean
#  end_date               :date
#  half_day_on_end_date   :boolean
#  approver_id            :integer
#  date_approved          :date
#  decadays               :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  date_rejected          :date
#  active                 :boolean
#  deactivation_pending   :boolean          default(FALSE)
#

class BookedHoliday < ActiveRecord::Base

  include Comparable

  attr_accessible :approver_id, :date_approved, :end_date, :half_day_on_end_date, :half_day_on_start_date, :num_days, :start_date, :user_id, :holiday_year_id, :date_rejected, :active, :deactivation_pending

  default_scope   where(:active => true)

  belongs_to      :approver,
                  :class_name => User

  belongs_to      :holiday_year

  belongs_to      :user


  before_save     :set_num_days

  validates       :approver_id, numericality: true, allow_nil: true
  validates       :user_id, numericality: true
  validates       :start_date, :end_date, presence: true
  validates       :holiday_year_id, presence: true, numericality: true
  validates       :active, :inclusion => { :in => [true, false] }

  validates_with  PeriodValidator



  # Finders


  def self.all_future
    self.where('end_date >= ?', Date.today).order('start_date')
  end


  def self.all_for_period(start_date, end_date)
    self.where('(end_date >= ? AND end_date <= ?) OR (start_date >= ? AND start_date <= ?)', start_date, end_date, start_date, end_date).order('start_date')
  end

  

  def self.by_year_and_user(year_id, user_id)
    self.where('holiday_year_id = ? and user_id = ?', year_id, user_id).order('start_date')
  end


  # returns the last BookedHoliday record for the same user and holiday year whose start date is before the start date of <tt>rec</tt>.
  # @param [BookedHoliday] rec : A BookedHoliday record.  This method will return the last BookedHoliday records whose start date is before <tt>rec</tt>'s start date.
  # @param [Hash] options : An options hash which may contain the key :exclude_rejected, which can either be true or false.  If true, then rejected records will be
  # excluded from the search.  Default it true.
  def self.last_before_start(rec, options = {} )
    @exclude_rejected = options.has_key?(:exclude_rejected) ? options[:exclude_rejected] : true
    arel = BookedHoliday.where('holiday_year_id = ? and user_id = ? and start_date <= ?', rec.holiday_year_id, rec.user_id, rec.start_date)
    arel = rec.new_record? ? arel : arel.where('id != ?', rec.id)
    arel = @exclude_rejected == true ? arel.where('date_rejected is null') : arel
    arel.order('start_date DESC').first
  end

  # returns the last BookedHoliday record for the same user and holiday year whose end date is before the end_date of <tt>rec</tt>.
  # @param [BookedHoliday] rec : A BookedHoliday record.  This method will return the last BookedHoliday records whose end date is before <tt>rec</tt>'s start date.
  # @param [Hash] options : An options hash which may contain the key :exclude_rejected, which can either be true or false.  If true, then rejected records will be
  # excluded from the search.  Default it true. 
  def self.last_before_end(rec, options = {} )
    @exclude_rejected = options.has_key?(:exclude_rejected) ? options[:exclude_rejected] : true
    arel = BookedHoliday.where('holiday_year_id = ? and user_id = ? and start_date <= ?', rec.holiday_year_id, rec.user_id, rec.end_date)
    arel = rec.new_record? ? arel : arel.where('id != ?', rec.id)
    arel = @exclude_rejected == true ? arel.where('date_rejected is null') : arel
    arel.order('start_date DESC').first
  end




  # Returns an array of the booked holidays awaiting approval by the manager
  # @param [User] manager : The user object representing the managers whose staff's holiday requests we wish to return
  def self.awaiting_approval_by(manager) 
    staff_ids = manager.staff.map(&:id)
    self.where('approver_id is null and user_id in (?)', staff_ids)
  end



  # General methods

  # returns the balance of holidays for this user if this is approved
  def decadays_balance_if_approved
    # get all the other booked and waiting approval for this year and user excluding this one
    other_hols = self.class.where('holiday_year_id = ? and user_id = ? and id != ? and date_rejected is null and active = 1', self.holiday_year_id, self.user_id, self.id)
    other_hols_decadays = other_hols.sum(&:decadays)
    allowance = Allowance.for_year_and_user(self.holiday_year_id, self.user_id)
    set_num_days
    new_balance = allowance.total_decadays - other_hols_decadays - self.decadays
    new_balance
  end


  # Enables sorting by start_date within user_id
  def <=>(other)
    sort_key <=> other.sort_key
  end


  def sort_key
    sprintf('%04d%s', self.user_id, self.start_date.strftime('%Y%m%d'))
  end


  def in_future?
    self.start_date > Date.today
  end



  def in_past?
    !in_future?
  end


  def deletion_pending?
    self.deactivation_pending
  end



  # deactivates a booked holiday.  If the holiday is in the past, then a request is sent to the manager, and only the manager can de-activate it.
  def deactivate!
    flash = ''
    if in_future?
      flash = deactivate_future_booked_holiday
    else
      flash = request_past_booked_holiday_deactivation
    end
    flash
  end



  def deactivate_future_booked_holiday
    self.active = false
    self.save!
    BookedHolidayMailer.future_booked_holiday_deleted_mail(self).deliver
    "Booked Holiday #{self.decorate} has been deleted and your manager notified"
  end



  def request_past_booked_holiday_deactivation
    self.deactivation_pending = true
    self.save!
    BookedHolidayMailer.past_booked_holiday_deleted_mail(self).deliver
    "Booked Holiday #{self.decorate} is in the past, and your manager has been requested to delete this holiday."
  end



  def approved?
    !self.date_approved.nil?
  end

  def rejected?
    !self.date_rejected.nil?
  end

  def unapproved?
    self.approver_id.nil? && self.date_rejected.nil?
  end


 
  def num_days
    self.decadays.nil? ? 0.0 : self.decadays / 10.0
  end


  # returns two dates suitable for 
  def start_date_for_calendar_display
    self.start_date - calendar_leeway
  end



  def end_date_for_calendar_display
    self.end_date + calendar_leeway
  end




  def approve!(approver)
    update_attributes(approver_id: approver.id, date_approved: Date.today)
  end


  def reject!(approver)
    update_attributes(approver_id: approver.id, date_rejected: Date.today)
  end


  # returns true if the given date falls within the holiday
  def holiday?(date)
    return false if date < self.start_date || date > self.end_date
    return true
  end

  # returns true if the given date is a half day 
  def half_day?(date)
    return one_half_day_holiday?(date) if one_day_holiday? 
    if date == self.start_date
      return self.half_day_on_start_date
    elsif date == self.end_date
      return self.half_day_on_end_date
    end
    return false  
  end



  def self.existing_holiday_overlaps?(rec)
    start_overlaps = false
    end_overlaps = false

    # last_before_my_start = BookedHoliday.last_starting_before(rec.holiday_year_id, rec.user_id, rec.start_date)
    last_before_my_start = BookedHoliday.last_before_start(rec)
    last_before_my_end   = BookedHoliday.last_before_end(rec)
    
    start_overlaps = true if last_before_my_start && last_before_my_start.end_date >= rec.start_date
    end_overlaps = true if last_before_my_end && last_before_my_end.start_date >= rec.start_date

    result = start_overlaps || end_overlaps
    start_overlaps || end_overlaps
  end




  def set_num_days
    if self.active?
      calculator = WorkingDayCalculator.new(self)
      self.decadays = calculator.decadays
    else
      self.decadays = 0
    end
  end
    




  private


  def one_day_holiday?
    self.start_date == self.end_date
  end


  def one_half_day_holiday?(date)
    if self.start_date == date && self.end_date == date
      return self.half_day_on_end_date? || self.half_day_on_start_date
    end
    return false
  end



  # REturns the number of days to subtract from the start date and end to the end date when displaying a calendar
  def calendar_leeway
    num_calendar_days = (self.end_date - self.start_date).to_i
    (30 - num_calendar_days)/2
  end


end

app/controllers/booked_holidays_controller.rb
class BookedHolidaysController < ApplicationController
  
  load_resource :booked_holiday, :only => :index
  authorize_resource :booked_holiday
  


  def index
    @year            = HolidayYear.now
    @uhs_cy          = UserHolidaySet.new(@year.id, current_user.id)
    @uhs_ny          = UserHolidaySet.new_for_next_year(current_user.id)          # will be nil if no HolidayYear record exists for next year
    @months          = get_array_of_dates
    @booked_holidays = @booked_holidays.all_future
    @booked_holidays = @booked_holidays.decorate
  end


  def create
    @bhc = BookedHolidayCreator.new(params)
    if @bhc.valid?
      flash[:notice] = @bhc.notes
    else
      flash[:errors] = @bhc.errors
    end
  end


  def destroy
    bh = BookedHoliday.find(params[:id])
    msg = bh.deactivate!
    flash[:alert] = msg
    redirect_to action: :index
  end



  def approve
    approver = BookedHolidayApprover.new(current_user, params)
    approver.run if approver.valid?
    flash[:alert] = approver.notes
    redirect_to action: :index
  end


  def approve_deletion
    @booked_holiday = BookedHoliday.find(params[:id]).decorate
    @user = @booked_holiday.user
  end



  def confirm_deletion
    # sample params:
    # {"email_message"=>"This is the message I want ot give.", "approve_deletion"=>"", "action"=>"confirm_deletion", "controller"=>"booked_holidays", "id"=>"18"}
    # or
    # {"email_message"=>"No way Jose!", "deny_deletion"=>"", "action"=>"confirm_deletion", "controller"=>"booked_holidays", "id"=>"18"}
    #
    msg = BookedHolidayDeletionProcessor.new(params).run
    flash[:notice] = msg
    redirect_to booked_holidays_path
  end


  private

  def get_array_of_dates
    dates = []
    d = Date.today
    12.times do
      dates << d
      d += 1.month
    end
    dates
  end



end

app/views/booked_holidays/_booked_holiday_row.haml
%td= ah.start_date.dmy
%td= ah.end_date.dmy
%td= ah.num_days
%td= ah.approval_status
%td= ah.date_approved.nil? ? ' ' : ah.date_approved.dmy
%td=  render_cell :booked_holiday_action, :show, :booked_holiday => ah

app/views/booked_holidays/_month_links.haml
%h5 View Holiday Calendars
  %table
    - 4.times do
        %tr
          - 3.times do
            %td
              = months.shift.strftime('%B')

       

app/views/booked_holidays/_outstanding_requests.haml
.row
%hr
%h3 Holiday requests awaiting your approval
=form_tag approve_booked_holidays_path do
  %table.table.table-bordered.table-condensed.span10
    %thead
      %tr
        %th Staff Member
        %th From
        %th To 
        %th Num Working Days
        %th Balance if Approved
        %th Action
    %tbody
    - uhs.user.outstanding_requests.each do |bh|
      - bh = bh.decorate
      %tr.success
        %td= bh.user.name
        %td= bh.start_date.dmy
        %td= bh.end_date.dmy
        %td= bh.num_days
        %td= bh.balance_if_approved
        %td
          = check_box_tag "approve_#{bh.id}", 1, false, {id: "approve_#{bh.id}", class: 'checkbox'} 
          Approve
          = check_box_tag "reject_#{bh.id}", 1, false, {class: 'checkbox'} 
          Reject
          &nbsp;
          =link_to 'View', calendar_show_path(:id => bh)
  %button.btn.btn-danger{:type => 'submit'} Approve/Reject Requests

app/views/booked_holidays/_request_holiday_form.haml
%h3 Request Holiday

= form_tag(booked_holidays_path, :class => 'form-search inline') do

  .control-group
    = label_tag 'start_date', 'From', :class => 'control-label'
    .controls
      .input-prepend.time-picker-input
        .add-on
          %i.icon-time
        = text_field_tag  :start_date, nil, placeholder: 'Click to set start date', class: 'span3 datetime_form'
      %label.checkbox
      = check_box_tag :half_day_on_start_date, 1, false, {class: 'checkbox'}
      Half Day?

  .control-group
    = label_tag 'end_date', 'Until', :class => 'control-label'
    .controls
      .input-prepend.time-picker-input
        .add-on
          %i.icon-time
        = text_field_tag  :end_date, nil, placeholder: 'Click to set end date', class: 'span3 datetime_form'
      %label.checkbox
      = check_box_tag :half_day_on_end_date, 1, false, {class: 'checkbox'}
      Half Day?

      


  = hidden_field_tag :user_id, uhs.user_id
  
  %button.btn.btn-primary{:type => 'submit'} Send Request

app/views/booked_holidays/_staff_booked_holidays.haml
.row
%hr
%h3 Staff Booked Holidays
%table.table.table-bordered.table-condensed.span10
  %thead
    %tr
      %th Staff Member
      %th From
      %th To
      %th Num Working Days
      %th Action
  %tbody
    - @booked_holidays.each do |bh|
      %tr
        %td= bh.user.name
        %td= bh.start_date_human
        %td= bh.end_date_human
        %td= bh.num_days
        %td= link_to 'View', calendar_show_path(:id => bh)

app/views/booked_holidays/_summary.haml
%h5= uhs.year_description

%table.table.table-bordered.table-condensed
  %tr.success
    %td Entitlement
    %td= uhs.num_allowance_days
  %tr.success
    %td Brought Forward from last year
    %td= uhs.num_brought_forward_days
  %tr.success
    %td Total Days this year
    %td= uhs.total_num_days
  %tr.error
    %td Approved Booked Holidays
    %td= uhs.num_approved_holidays
  %tr.error
    %td Booked Holidays awaiting approval
    %td= uhs.num_unapproved_holidays
  %tr.error
    %td Days still left to take this year
    %td= uhs.num_days_available

app/views/booked_holidays/_user_booked_holidays.haml
.row
%hr
%h3 
  Your Booked Holidays
  = uhs.year.description
%table.table.table-bordered.table-condensed.span10
  %thead
    %tr
      %th From
      %th To 
      %th Num Working Days
      %th Approved By
      %th Approval Date
      %th Action
  %tbody
    - uhs.approved_holidays.each do |ah|
      %tr.success
        =render :partial => 'booked_holiday_row', :locals => {:ah => ah}
        
    - uhs.unapproved_holidays.each do |ah|
      %tr.info
        =render :partial => 'booked_holiday_row', :locals => {:ah => ah}
        
    - uhs.rejected_holidays.each do |ah|
      %tr.error


- if uhs.hols_next_year?
  .row
  %h3 
    Holidays booked for 
    = uhs.next_year.description
  %table.table.table-bordered.table-condensed.span10
    %thead
      %tr
        %th From
        %th To 
        %th Num Working Days
        %th Approved By
        %th Approval Date
        %th Action
    %tbody
      - uhs.ny_approved_holidays.each do |ah|
        %tr.success
          =render :partial => 'booked_holiday_row', :locals => {:ah => ah}
          
      - uhs.ny_unapproved_holidays.each do |ah|
        %tr.info
          =render :partial => 'booked_holiday_row', :locals => {:ah => ah}
          
      - uhs.ny_rejected_holidays.each do |ah|
        %tr.error

app/views/booked_holidays/approve_deletion.haml
%h2 Booked Holiday Deletion Request.
%p
  = "#{@user.name} has asked requested the deletion of holiday #{@booked_holiday}."
  

%p
  This start date for this holiday is today, or earlier, and therefore you approval is required to delete this holiday.

%p 
  = "Please approve or deny, and optionally send a message to #{@user.name}."




= form_tag(confirm_deletion_booked_holiday_path(@booked_holiday), :class => 'form-search inline') do
  %row.span10
    %textarea.form-control.field.span8{:name => 'email_message', :rows => 8, :placeholder => "Any text you type here will be included in an emaill message to #{@user.name}"}
  %row.span10
    %p
    %button.btn.btn-success{:name => 'approve_deletion', :type => 'submit'} Approve Deletion Request
    &nbsp;&nbsp;
    %button.btn.btn-danger{:name => 'deny_deletion',:type => 'submit'} Deny Deletion Request
    %p
    %p

app/views/booked_holidays/create.haml
%h2 Booked Holiday Request.



%p 
  - if @bhc.valid?
    Your Holiday Request below has been sent to
    = @bhc.user.manager.name
    for approval.

    %ul
      - @bhc.booked_holidays.each do |booked_holiday|
        %li= booked_holiday.decorate.to_s
  - else
    Please correct the error and try again.

app/views/booked_holidays/index.haml
.row-fluid
  %h2 Staff Holiday Booking System

  %h3 
    Summary for 
    = @uhs_cy.user.name

.row-fluid
  .span4#current_year_summary
    =render :partial => 'summary', :locals => {:uhs => @uhs_cy}

  .span4#next_year_summary
    - unless @uhs_ny.nil?
      =render :partial => 'summary', :locals => {:uhs => @uhs_ny}

  .span4 
    %h5 View Holiday Calendars
    %table.table
      - 4.times do
        %tr
          - 3.times do
            %td
              - date = @months.shift
              = link_to date.strftime('%B'), calendar_show_path(:date => date)
    %p
    - if can?(:read, :admin)
      = link_to "View Details for all Staff", admin_index_path


.row
%hr
=render partial: 'request_holiday_form', :locals => {:uhs => @uhs_cy}



-if @uhs_cy.approved_or_unapproved_holidays.any?
  =render :partial => 'user_booked_holidays', :locals => {:uhs => @uhs_cy}


-if @uhs_cy.user.has_outstanding_requests?
  =render :partial => 'outstanding_requests', :locals => {:uhs => @uhs_cy}
  
     
-if @uhs_cy.user.is_manager?
  =render :partial => 'staff_booked_holidays', :locals => {:booked_holidays => @booked_holidays}
  