config/routes.rb
StaffHols::Application.routes.draw do
  get "admin/index"

  get "calendar/show"

  authenticated :user do
    root :to => 'booked_holidays#index'
  end
  root :to => "booked_holidays#index"
  devise_for :users
  resources :users
  resources :booked_holidays do
    collection do
      post :approve
    end
    member do
      get :approve_deletion
      post :confirm_deletion
    end
  end
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String) || msg.is_a?(Array)
    %div{ :class => "#{flash_class(name)}" }
      %a.close{"data-dismiss" => "alert"} ×
      - if msg.is_a?(String)
        = content_tag :div, msg, :id => "flash_#{name}"
      - else
        %ul
          - msg.each do |item|
            %li= item
          

app/views/layouts/_navigation.html.haml
= link_to "StaffHols", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    - if current_user.is_admin? || current_user.is_manager?
      %li
        = link_to "Staff Holiday Overview", admin_index_path
    - if current_user.is_admin?
      %li
        = link_to 'User Administration', users_path
        
      

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "StaffHols"
      %meta{:content => content_for?(:description) ? yield(:description) : "StaffHols", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
            %p.muted
              Revision: 
              = @revision
      / ! end of .container
    / ! end of #main